### ISSUE TITLE
Inbound hooks?

### ISSUE THREAD

**Issue by RFC1920** [jacobcoughenour/jpipes-legacy#1]
I wonder if you can add something like the following to JPipes?  I was hoping to use this from NoDecay to avoid decaying JPipes if nodecay is set.

This is because of a change made awhile back to NoDecay that tries to override other plugins' action in OnEntityTakeDamage (for decay only).

`
        private bool AllowDecay() => !configData.nodecay;

        private bool IsPipe(BaseCombatEntity entity)
        {
            jPipeSegChild p = entity.GetComponent<jPipeSegChild>();
            if (p != null && p.pipe != null)
            {
                return true;
            }
            return false;
        }​`

**Comment by jacobcoughenour** [comment]
Added IsPipe() and IsNoDecayEnabled() in v0.6.8.

Let me know if that works out.

**Comment by RFC1920** [comment]
Thank you.
