### ISSUE TITLE
vending machine bug when load Jpipe plugin

### ISSUE THREAD

**Issue by olajmuvek** [jacobcoughenour/jpipes-legacy#3]
i have a VendingMachine problem when i load your JPipe plugin.
When i place a Vending machine, and i try to use it i have the following bug:

if the amount of scrap (or anything) in the player’s inventory is equal to the value in the Vending Machine to buy stuff,
the buying material will fall out from vending machine rear side during the exchange. I not use for it a Jpipe, but the plugin is loaded.

If greater the amount of currency, woring all ok. But equal of the currency, the vending machine drops out.

When i unload the JPIPE plugin, the vending machine works fine.

Please help to me, to use Jpipe without vending machine problem.

**Comment by jacobcoughenour** [comment]
This plugin is no longer maintained. Use [syncPipes](https://umod.org/plugins/sync-pipes) instead.
