### ISSUE TITLE
Prioritize item filter over pipes without a filter

### ISSUE THREAD

**Issue by Kajvdh** [jacobcoughenour/jpipes-legacy#4]
Hi,

When having a box with multiple output pipes and some of these have a filter - it seems like items that are filtered by one of the pipes might still get sorted to the pipes that have no filter configured.

Is this something on the roadmap that might get fixed anytime soon?

Kind regards,

Kaj

**Comment by mjellings** [comment]
I came here to try and look at the code to check the same.  I have an idea for a layout but it would need filtered pipes to act on items first.

Any update on if this is possible or in the works for a future version?

**Comment by Kajvdh** [comment]
Hi @mjellings,

In the meantime I found this project that offers the same functionality but added a priority system, which makes this behaviour possible. See: https://github.com/Joe90384/syncPipes

I'm not sure if this helps you

**Comment by mjellings** [comment]
This is great, thanks.  I've just had a friend check and although I thought our server was running jPipes it's actually already running syncPipes so that's great :)  Cheers

**Comment by jacobcoughenour** [comment]
> In the meantime I found this project that offers the same functionality but added a priority system, which makes this behaviour possible. See: https://github.com/Joe90384/syncPipes

> This is great, thanks. I've just had a friend check and although I thought our server was running jPipes it's actually already running syncPipes so that's great :) Cheers

This is the first I'm hearing about syncPipes. I looked into it and it looks like a great spiritual successor to JPipes. 

I added a notice at the top of the README and the uMod page linking to syncPipes.
